server:
  port: 8092
  
dubbo:
  application:
    name: Seata-QFDMY-Account-Service
  registry:
    address: zookeeper://h1:2181
  protocol:
    name: dubbo
    port: 20881
 
spring:
  application:
    name: Seata-QFDMY-Account-Service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3307/seata
#    url: jdbc:mysql://localhost:3306/seata
    username: root
    password: zzw1234
  cloud:
    alibaba:  #seata配置 
      seata:
        tx-service-group: zzw_seata_group

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:mapper/*.xml
  type-aliases-package: com.asiainfo.entity